---
title: "AFATDS"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  pdf_document: default
  html_document:
    code_folding: hide
    fig_align: center
    fig_height: 6
    fig_width: 12
    keep_md: yes
editor_options:
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, caret)

theme_set(theme_bw())
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

##7R

```{r 7R}
M119A2.7R <- M795
Elev <- glm(Mil~poly(M,20,raw=TRUE), data = M119A2.7R)
test <- data.frame(M=11100)
predict(Elev, test, type = "response")

plot(M119A2.7R$M,M119A2.7R$Mil,pch=19)
lines(x,predict(Elev,data.frame(M=M119A2.7R$M)),col="red")

```

```{r 4h}
load(file = "4H.rda")
M232.4H <- M795
curve <- glm(Elev~poly(Range,16,raw=TRUE), data = M232.4H)
test <- data.frame(Range=6100)
predict(curve, test, type = "response")

plot(M232.4H$Range,M232.4H$Elev,pch=19)
lines(M232.4H$Range,predict(curve,data.frame(Range=M232.4H$Range)),col="red")
```




```{r}
x <- c(32,64,96,118,126,144,152.5,158)
y <- c(99.5,104.8,108.5,100,86,64,35.3,15)
#we will make y the response variable and x the predictor
#the response variable is usually on the y-axis
plot(x,y,pch=19)

#fit first degree polynomial equation:
fit  <- lm(y~x)
#second degree
fit2 <- lm(y~poly(x,2,raw=TRUE))
#third degree
fit3 <- lm(y~poly(x,3,raw=TRUE))
#fourth degree
fit4 <- lm(y~poly(x,4,raw=TRUE))
#generate range of 50 numbers starting from 30 and ending at 160
xx <- seq(30,160, length=50)
plot(x,y,pch=19,ylim=c(0,150))
lines(xx, predict(fit, data.frame(x=xx)), col="red")
lines(xx, predict(fit2, data.frame(x=xx)), col="green")
lines(xx, predict(fit3, data.frame(x=xx)), col="blue")
lines(xx, predict(fit4, data.frame(x=xx)), col="purple")

summary(fit)
summary(fit2)
summary(fit3)
summary(fit4)
```

