---
title: "Artillery Deflection Steps"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  pdf_document: default
  html_document:
    code_folding: hide
    fig_align: center
    fig_height: 6
    fig_width: 12
    keep_md: yes
editor_options:
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, shiny, ggmap, mgrs, geosphere)

theme_set(theme_bw())
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## Base Map

```{r bm}
library(ggmap)
register_google(key = "AIzaSyAfnLNZjvYdMx-cyga_qA1oJ6P36dRGalA") 
octc <- get_map(location = "11TNH7000080000", maptype="terrain" ,scale=4, zoom =10)
map<-octc
```


## Shiny

```{r shiny}

ui <- fluidPage(
  h1("Compute Deflection"),
  sidebarLayout(
    sidebarPanel(
       radioButtons(inputId = "maptype",label = "Pick a Map Type",choices = c("terrain","satellite","roadmap","hybrid")),
       textInput("MGRS","Center MGRS", "11TNH7000080000"),
       textOutput("Center"),
       textOutput("Lon"),
       textOutput("Lat"),
       numericInput("aof","Azimuth of Fire",2000,min = 0,max = 6399),
       textOutput("dist"),
       textOutput("az"),
       textOutput("defl"),
       actionButton(inputId = "get_map", label = "Get Map")
    ),
    mainPanel(
     
     plotOutput("mapd", click = "clickMap", width = "600px", height = "600px")
              )
  )
)
server <- function(input, output) {
  
  passmap <- reactive({})
  
  observeEvent(input$get_map, {  
    centerll <- mgrs_to_latlng(input$MGRS)
    output$Center <- renderText({"Center"})
    output$Lon <- renderText({paste("Longitude: ",centerll$lng)})
    output$Lat <- renderText({paste("Latitude: ",centerll$lat)})
    aoftip <- destPoint(c(centerll$lng,centerll$lat),input$aof/6400*360,
                              10000)
    amap <- get_map(location = input$MGRS, maptype=input$maptype ,scale=4, 
                    zoom =10)
    output$mapd <- renderPlot({
      ggmap(amap) + ggtitle(input$maptype) +
        geom_point(aes(centerll$lng, centerll$lat), size = 5) +
        geom_segment(x=centerll$lng, y= centerll$lat, xend=aoftip[1,1], 
                         yend = aoftip[1,2],size = 1, 
                         arrow = arrow(length = unit(0.1, "inches")))
          })
        })
  
  observeEvent(input$clickMap, {
    x <- input$clickMap$x
    y <- input$clickMap$y
    aof <- input$aof
    df <- data.frame(long = x, lat = y)
    aoftip <- destPoint(c(centerll$lng,centerll$lat),input$aof/6400*360,
                              10000)
    
    dist <- trunc(distGeo(c(centerll$lng,centerll$lat),c(x,y)))
    output$dist <- renderText({paste("Distance to Target: ", dist, "m")})
    
    az <- trunc(bearing(c(centerll$lng,centerll$lat),c(x,y))*6400/360)
    if (az<0) {az <- az + 6400}
    output$az <- renderText({paste("Azimuth to Target: ", az, "mils")})
    
    defl <- 3200+(aof-az)
    if (defl < 0) {defl <- defl + 6400}
    output$defl <- renderText({paste("Deflection to Target: ", defl,
                                         "mils")})

    output$mapd <- renderPlot({
      ggtitle("with target") +
        geom_point(data = df, aes(long, lat), color= "red" ,size = 5) +
        geom_point(aes(centerll$lng, centerll$lat), color= "Blue", size = 5) +
        geom_segment(x=centerll$lng, y= centerll$lat, xend=aoftip[1,1], 
                         yend = aoftip[1,2],size = 1, color = "blue",
                         arrow = arrow(length = unit(0.1, "inches")))
        })
    })
}
shinyApp(ui, server)
```
