---
title: "Artillery Deflection"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  pdf_document: default
  html_document:
    code_folding: hide
    fig_align: center
    fig_height: 6
    fig_width: 12
    keep_md: yes
editor_options:
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, shiny, ggmap, mgrs, shinydashboard)

theme_set(theme_bw())
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## Base Map

```{r bm}
library(ggmap)
register_google(key = "AIzaSyAfnLNZjvYdMx-cyga_qA1oJ6P36dRGalA") 
octc <- get_map(location = "11TNH7000080000", maptype="terrain" ,scale=4, zoom =10)
map <- octc
```


## Shiny

```{r shiny}
startll <- mgrs_to_latlng("11TNH7000080000")
centerll <- startll
ui <- fluidPage(
  h1("Compute Deflection"),
  sidebarLayout(
    sidebarPanel(
       radioButtons(inputId = "maptype",label = "Pick a Map Type",choices = c("terrain","satellite","roadmap","hybrid")),
       textInput("MGRS","Center MGRS", "11TNH7000080000"),
       textOutput("Lat_Lon"),
       actionButton(inputId = "get_map", label = "Get Map"),
       numericInput("aof","Azimuth of Fire",2000,min = 0,max = 6399)
    ),
    mainPanel(
     
     plotOutput("mapd", click = "clickMap", width = "600px", height = "600px")
              )
  )
)
server <- function(input, output) {
  
      output$mapd <- renderPlot({
        input$get_map
        isolate({
          centerll <- mgrs_to_latlng(input$MGRS)
          output$Lat_Lon <- renderText({ 
    paste("Center Latitude Longitude:",centerll$lat,centerll$lng, sep=" ")
  })
          map <- get_map(location = input$MGRS, maptype=input$maptype ,scale=4, zoom =10)
          ggmap(map) + ggtitle(input$maptype) +
                geom_point(aes(centerll$lng, centerll$lat), size = 5)
          
                })
        
    })
       observeEvent(input$clickMap, {
        x <- input$clickMap$x
        y <- input$clickMap$y
        df <- data.frame(long = x, lat = y)
        output$mapd <- renderPlot({
            ggmap(map)  + ggtitle("without map projection") +
                geom_point(data = df, aes(long, lat), color= "red" ,size = 5) +
                geom_point(aes(centerll$lng, centerll$lat), color= "Blue", size = 5)
        })
    })
}
shinyApp(ui, server)
```

```{r other}
points <- data.frame(lon=c(-122,-121.9,-121.8,-121.7),lat=c(37.2,37.2,37.2,37.2))
map <- get_map(location = c(lon = mean(points$lon),lat = mean(points$lat)),
               maptype="roadmap",scale=2, zoom =11)


ui <- fluidPage (
    plotOutput(outputId="mapOut",
               ##########################################################
               # force the ratio of the width and height so that the map
               # appears as square
               width=530, height=500,  
               click = "plot_click"
    ),
    verbatimTextOutput(outputId="info"),
    verbatimTextOutput(outputId="coords")

)


server <- function(input,output) {

    output$mapOut <- renderPlot({
        mapPoints <-  ggmap(map, extent = "normal") + 
            geom_point(aes(x = lon, y = lat),size=8,colour="black", data=points)
        #########################################################
        # add coord_cartesian() to strip coord_map() from ggmap()
        mapPoints + coord_cartesian()
    })

    output$info <- renderPrint({
        ptClicked <- nearPoints(points, coordinfo = input$plot_click, 
                                threshold = 10, maxpoints = 1, 
                                xvar="lon", yvar="lat");
        data.frame(lon=ptClicked$lon,lat=ptClicked$lat);

    })

    output$coords <- renderText({
        paste0("x=", input$plot_click$x, "\ny=", input$plot_click$y)
    })
}

shinyApp(server = server, ui = ui)
```

```{r pc}
ui <- fluidPage(
    column(
        width = 6,
        plotOutput("map", click = "clickMap", width = 385, height = 400)
    )
)

server <- function(input, output) {
    # initial plot with and without projection
    output$map <- renderPlot({
        ggmap(map) + ggtitle("without map projection")
    })
    
    # plot after clicking on map with projection

    
    # plot after cliking on map without projection
    observeEvent(input$clickMap, {
        x <- input$clickMap$x
        y <- input$clickMap$y
        df <- data.frame(long = x, lat = y)
        output$map <- renderPlot({
            ggmap(map)  + ggtitle("without map projection") +
                geom_point(data = df, aes(long, lat), size = 5)
        })
    })
}

shinyApp(ui, server)
```

```{r leaf}
library(shiny)
library(sp)
library(shinydashboard)
library(leaflet)

#### Make a spatial data frame 
lats<-c(37.38,39)
lons<-c(-94,-95,-96)
df<-data.frame(cbind(lons,lats))
coordinates(df)<-~lons+lats

#### Define UI for application that draws a histogram
ui <- dashboardPage(

    dashboardHeader(
    ),

    # Sidebar layout with input and output definitions 
    dashboardSidebar(
    ),

    # Main panel for displaying outputs 
    dashboardBody(
                     h2("My Map", align="center"),
                     h5("Click anywhere to draw a circle", align="center"),
                     leafletOutput("mymap", width="100%", height="500px")
        ),
    )



#### Define server logic required to draw a histogram
server <- function(input, output) {

    output$mymap <- renderLeaflet({
                 m = leaflet(df,width="100%",height="100%") %>% 
                 addTiles()    %>%
                 addCircleMarkers()
    })


    observeEvent(input$mymap_click, {

        click <- input$mymap_click
        text<-paste("Latitude ", round(click$lat,2), "Longtitude ", round(click$lng,2))

        proxy <- leafletProxy("mymap")

        ## This displays the pin drop circle
        proxy %>% 
            clearGroup("new_point") %>%
            #clearMarkers(layerId=input$mymap_click$id) %>%
            #addPopups(click$lng, click$lat) %>%
            addCircles(click$lng, click$lat, radius=100, color="red", group = "new_point")

    })


}

# Run the application 
shinyApp(ui = ui, server = server)
```

