---
title: "Madness 2022 Model Test"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, DataCombine)
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

# Pull in

```{r}
KenPom <- read.csv("KenPom.csv")
ESPN_BPI <- read.csv("ESPN_BPI.csv")
BasRaf <- read.csv("BasRef.csv")
```

# Standard Team Name

```{r}
team_names <- sort(unique(KenPom$Team))
KPfix <- read.csv("KenPomFix.csv")
KenPom <- FindReplace(data = KenPom, Var = "Team", replaceData = KPfix,
                     from = "From", to = "To", exact = TRUE)
team_names <- sort(unique(KenPom$Team))
write.csv(data.frame(team_names),"teamnames.csv")

espn_Wrong <- sort(setdiff(ESPN_BPI$Team,team_names))
write.csv(data.frame(espn_Wrong),"espnwrong.csv")
```


