---
title: "Madness 2022 Model Test"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, gt, DT, data.table, caret, e1071)
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## Seed History

```{r}
#Load in Historical Games from 1985 through 2022
AllGames <- read.csv("All Games.csv")
AllGames <- AllGames %>% filter(Round != "PI")
#Build Seed History
seed.history <- data.frame(rbind(table(AllGames$W.Seed,AllGames$Round)))
seed.history$exp <- rowSums(seed.history)/144
gt(seed.history,,,TRUE)%>% 
   data_color(
    columns = 2:8, 
    colors = scales::col_numeric(
      palette = c("white","blue") %>% as.character(),
      domain = NULL
    )
  ) 
```

## Team Wins

```{r}
losers <- data.frame(rbind(table(AllGames$Loser,AllGames$Year)))
losers <- losers %>% add_rownames()
winners <- data.frame(rbind(table(AllGames$Winner,AllGames$Year)))
winners[winners > 0] <- winners[winners > 0] + 1
winners <- winners %>% add_rownames()
b2b <- left_join(losers,winners,by=c("rowname"="rowname"))
b2b[is.na(b2b)] <- 0
team.history <- cbind(b2b$rowname,b2b[,2:37]+b2b[,38:73])
colnames(team.history) <- c("team",seq(1985,2019,1),2021)
rownames(team.history) <- team.history$team
team.history <- team.history[-1,-1]
scale.v <- seq(.5,1,.5/35)
team.history$Exp <- colSums(t(team.history) * scale.v)
team.history[,1:36] <- team.history[,1:36] - 1
team.history[team.history == -1] <- NA
datatable(team.history)
```

## Team Seeds

```{r}
team.seed.w <- AllGames %>% filter(Round == 1) %>% select(c(2,6,7))
colnames(team.seed.w) <- c("Year","Seed","Team")
team.seed.l <- AllGames %>% filter(Round == 1) %>% select(c(2,9,10))
colnames(team.seed.l) <- c("Year","Seed","Team")
team.seed.long <- rbind(team.seed.w,team.seed.l)
team.seed.wide <- spread(team.seed.long, Year, Seed)
datatable(team.seed.wide)
```

## PASE

```{r}
x <- team.seed.wide
old <- 1:16
new <- seed.history$exp
for (i in old) {
x[x == i] <- new[i]
}

#setdiff(x$Team,rownames(team.history))

team.exp.wide <- x 
team.pase.wide <- cbind(team.history[,1:36]-x[,2:37])
team.pase <- data.frame(cbind(rowMeans(team.pase.wide, na.rm=TRUE)))
colnames(team.pase) <- "Pase"
datatable(team.pase)
```

## BPI

```{r}
pacman::p_load(tidyverse, rvest)
ESPN_BPI <- data.frame()
for (each_year in seq(from = 2008, to = 2021)){
  for (each_page in seq(from = 1, to = 7)) {
      link = paste0("https://www.espn.com/mens-college-basketball/bpi/_/view/bpi/season/",each_year,"/page/",each_page)
      page <- read_html(link)
      Year <- each_year
      RK <- page %>% html_nodes(".bpi__table td:nth-child(1)") %>% html_text()
      Team <- page %>% html_nodes(".team-names") %>% html_text()
      Conf <- page %>% html_nodes(".align-left+ td.align-left") %>% html_text()
      WL <- page %>% html_nodes(".align-left~ .align-left+ td") %>% html_text()
      BPI_OFF <- page %>% html_nodes("td:nth-child(5)") %>% html_text()
      BPI_DEF <- page %>% html_nodes("td:nth-child(6)") %>% html_text()
      BPI <- page %>% html_nodes("td:nth-child(7)") %>% html_text()
      ESPN_BPI <- rbind(ESPN_BPI,data.frame(Year,RK,Team,Conf,WL,BPI_DEF,BPI_OFF,BPI,stringsAsFactors = FALSE))
  }
}
datatable(ESPN_BPI)
```

# Practice Model
```{r}
load("AllCombine.rda")
years <- c(2008:2019,2021)
pyear <-2007 
acc<-NA
accy<-NA
```



```{r}

pyear <- pyear + 1
model_games <- AllCombine %>% filter(Year != pyear)
test_games <- AllCombine %>% filter(Year == pyear)
model <- lm(amv ~ .,data =model_games[,c(-5,-6,-8,-9,-10,-30)])
test_games$pmv <- predict(model, test_games, type = "response")
plot.new()
test_games %>% ggplot(aes(x=pmv,y=amv)) + geom_point() + 
  abline(c(0,min(test_games$amv)),c(0,max(test_games$amv)))

actual.P <- test_games$amv>0
p.P <- test_games$pmv>0

rp <- confusionMatrix(table(actual.P,p.P))
acc <- c(acc,rp$overall[1])
accy <- c(accy,pyear)
plot(accy,acc)
rp$overall[1]
pyear
```









