---
title: "Madness 2022 Model Test"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, DT, rvest, DataCombine,caret)
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## BPI

```{r}
ESPN_BPI <- data.frame()
for (each_year in seq(from = 2008, to = 2021)){
  for (each_page in seq(from = 1, to = 7)) {
      link = paste0("https://www.espn.com/mens-college-basketball/bpi/_/view/bpi/season/",each_year,"/page/",each_page)
      page <- read_html(link)
      Year <- each_year
      RK <- page %>% html_nodes(".bpi__table td:nth-child(1)") %>% html_text()
      Team <- page %>% html_nodes(".team-names") %>% html_text()
      Conf <- page %>% html_nodes(".align-left+ td.align-left") %>% html_text()
      WL <- page %>% html_nodes(".align-left~ .align-left+ td") %>% html_text()
      BPI_OFF <- page %>% html_nodes("td:nth-child(5)") %>% html_text()
      BPI_DEF <- page %>% html_nodes("td:nth-child(6)") %>% html_text()
      BPI <- page %>% html_nodes("td:nth-child(7)") %>% html_text()
      ESPN_BPI <- rbind(ESPN_BPI,data.frame(Year,RK,Team,Conf,WL,BPI_DEF,BPI_OFF,BPI,stringsAsFactors = FALSE))
  }
}
datatable(ESPN_BPI)
write.csv(ESPN_BPI,"ESPN_BPI.csv")
```

## KenPom

```{r}
KenPom <- data.frame()
for (each_year in seq(from = 2008, to = 2021)){
      link = paste0("https://kenpom.com/index.php?y=",each_year)
      page <- read_html(link)
      Year <- each_year
      RK <- page %>% html_nodes("td.hard_left") %>% html_text()
      Team <- page %>% html_nodes("td.next_left a") %>% html_text()
      Conf <- page %>% html_nodes(".conf a") %>% html_text()
      WL <- page %>% html_nodes("td.wl") %>% html_text()
      AdjEM <- page %>% html_nodes(".wl+ td") %>% html_text()
      AdjO <- page %>% html_nodes(".td-left:nth-child(6)") %>% html_text()
      AdjD <- page %>% html_nodes(".td-left:nth-child(8)") %>% html_text()
      SOSEM <- page %>% html_nodes(".divide:nth-child(14)") %>% html_text()
      SOSO <- page %>% html_nodes(".td-left:nth-child(16)") %>% html_text()
      SOSD <- page %>% html_nodes(".td-left:nth-child(18)") %>% html_text()
      KenPom <- rbind(KenPom,data.frame(Year,RK,Team,Conf,WL,AdjEM,AdjO,AdjD,SOSEM,SOSO,SOSD,stringsAsFactors = FALSE))
}
datatable(KenPom)
write.csv(KenPom,"KenPom.csv")
```

## BasRef

```{r}
BasRef <- data.frame()
for (each_year in seq(from = 2008, to = 2019)){
      link = paste0("https://www.sports-reference.com/cbb/seasons/",each_year,"-ratings.html")
      page <- read_html(link)
      Year <- each_year
      RK <- page %>% html_nodes("th.right") %>% html_text()
      Team <- page %>% html_nodes(".right+ .left a") %>% html_text()
      Conf <- page %>% html_nodes(".left+ .left a") %>% html_text()
      W <- page %>% html_nodes(".right:nth-child(5)") %>% html_text()
      L <- page %>% html_nodes(".right:nth-child(6)") %>% html_text()
      Pts <- page %>% html_nodes(".right:nth-child(7)") %>% html_text()
      Opp <- page %>% html_nodes(".right:nth-child(8)") %>% html_text()
      Mov <- page %>% html_nodes(".right:nth-child(9)") %>% html_text()
      SOS <- page %>% html_nodes(".right:nth-child(11)") %>% html_text()
      OSRS <- page %>% html_nodes(".right:nth-child(13)") %>% html_text()
      DSRS <- page %>% html_nodes(".right:nth-child(14)") %>% html_text()
      SRS <- page %>% html_nodes(".right:nth-child(15)") %>% html_text()
      BasRef <- rbind(BasRef,data.frame(Year,RK,Team,Conf,W,L,Pts,Opp,Mov,SOS,OSRS,DSRS,SRS,stringsAsFactors = FALSE))
}
      link = paste0("https://www.sports-reference.com/cbb/seasons/2021-ratings.html")
      page <- read_html(link)
      Year <- 2021
      RK <- page %>% html_nodes("th.right") %>% html_text()
      Team <- page %>% html_nodes(".right+ .left a") %>% html_text()
      Conf <- page %>% html_nodes(".left+ .left a") %>% html_text()
      W <- page %>% html_nodes(".center+ .right") %>% html_text()
      L <- page %>% html_nodes(".right:nth-child(7)") %>% html_text()
      Pts <- page %>% html_nodes(".right:nth-child(8)") %>% html_text()
      Opp <- page %>% html_nodes(".right:nth-child(9)") %>% html_text()
      Mov <- page %>% html_nodes(".right:nth-child(10)") %>% html_text()
      SOS <- page %>% html_nodes(".right:nth-child(12)") %>% html_text()
      OSRS <- page %>% html_nodes(".right:nth-child(14)") %>% html_text()
      DSRS <- page %>% html_nodes(".right:nth-child(15)") %>% html_text()
      SRS <- page %>% html_nodes(".right:nth-child(16)") %>% html_text()
      BasRef <- rbind(BasRef,data.frame(Year,RK,Team,Conf,W,L,Pts,Opp,Mov,SOS,OSRS,DSRS,SRS,stringsAsFactors = FALSE))
datatable(BasRef)
write.csv(BasRef,"BasRef.csv")
```

# Pull in

```{r}
AllGames <- read.csv("All Games.csv")
save(AllGames, file="AllGames.rda")
load("AllGames.rda")
KenPom <- read.csv("KenPom.csv")
ESPN_BPI <- read.csv("ESPN_BPI.csv")
BasRef <- read.csv("BasRef.csv")
```

# Standard Team Name

```{r}
team_names <- sort(unique(KenPom$Team))
KPfix <- read.csv("KenPomFix.csv")
KenPom <- FindReplace(data = KenPom, Var = "Team", replaceData = KPfix,
                     from = "From", to = "To", exact = TRUE)
team_names <- sort(unique(KenPom$Team))
write.csv(data.frame(team_names),"teamnames.csv")

espn_Wrong <- sort(setdiff(ESPN_BPI$Team,team_names))
write.csv(data.frame(espn_Wrong),"espnwrong.csv")
espnfix <- read.csv("espnfix.csv")
ESPN_BPI <- FindReplace(data = ESPN_BPI, Var = "Team", replaceData = espnfix,
                     from = "From", to = "To", exact = TRUE)
ESPN_BPI$Team <- gsub("\\(","",ESPN_BPI$Team)

BR_Wrong <- sort(setdiff(BasRef$Team,team_names))
write.csv(data.frame(BR_Wrong),"BRwrong.csv")

BRfix <- read.csv("BRfix.csv")
BasRef <- FindReplace(data = BasRef, Var = "Team", replaceData = BRfix,
                     from = "From", to = "To", exact = TRUE)
BasRef$Team <- gsub("\\)","",BasRef$Team)


```

# Save

```{r}
save(KenPom, file="KenPom.rda")
save(ESPN_BPI, file="ESPN_BPI.rda")
save(BasRef, file="BasRef.rda")
```

# Now Combine

```{r}
load("AllGames.rda")
load("BasRef.rda")
load("ESPN_BPI.rda")
load("KenPom.rda")
AllGames08 <- AllGames %>% filter(Year >= 2008) %>% select(c(-1,-4))
BasRef08 <- BasRef %>% select(c(-1,-3))
ESPN_BPI08 <- ESPN_BPI %>% select(c(-1,-3,-5,-6))
KenPom08 <- KenPom %>% select(c(-1,-3,-5,-6))
stage1 <- left_join(AllGames08,BasRef08,by=c("Year"="Year","Winner"="Team"))
stage2 <- left_join(stage1,ESPN_BPI08,by=c("Year"="Year","Winner"="Team"))
stage3 <- left_join(stage2,KenPom08,by=c("Year"="Year","Winner"="Team"))
stage4 <- left_join(stage3,BasRef08,by=c("Year"="Year","Loser"="Team"),suffix = c("_W","_L"))
stage5 <- left_join(stage4,ESPN_BPI08,by=c("Year"="Year","Loser"="Team"),suffix = c("_W","_L"))
stage6 <- left_join(stage5,KenPom08,by=c("Year"="Year","Loser"="Team"),suffix = c("_W","_L"))
stage6$amv <- stage6$W.Score-stage6$L.Score
AllCombine <- stage6
save(AllCombine, file="AllCombine.rda")
```
# Now Combine

```{r}
FUGames <- read.csv("FUAllGames.csv")
load("BasRef.rda")
load("ESPN_BPI.rda")
load("KenPom.rda")
AllGames08 <- FUGames %>% filter(Year >= 2008) %>% select(c(-3))
BasRef08 <- BasRef %>% select(c(-1,-3))
ESPN_BPI08 <- ESPN_BPI %>% select(c(-1,-3,-5,-6))
KenPom08 <- KenPom %>% select(c(-1,-3,-5,-6))
stage1 <- left_join(AllGames08,BasRef08,by=c("Year"="Year","F.Team"="Team"))
stage2 <- left_join(stage1,ESPN_BPI08,by=c("Year"="Year","F.Team"="Team"))
stage3 <- left_join(stage2,KenPom08,by=c("Year"="Year","F.Team"="Team"))
stage4 <- left_join(stage3,BasRef08,by=c("Year"="Year","U.Team"="Team"),suffix = c("_F","_U"))
stage5 <- left_join(stage4,ESPN_BPI08,by=c("Year"="Year","U.Team"="Team"),suffix = c("_F","_U"))
stage6 <- left_join(stage5,KenPom08,by=c("Year"="Year","U.Team"="Team"),suffix = c("_F","_U"))
stage6$amv <- stage6$F.Score-stage6$U.Score
AllCombine <- stage6
save(AllCombine, file="AllCombine.rda")
```



# Practice Model

```{r}
years <- c(2008:2019,2021)
pyear <- sample(years,1)
model_games <- AllCombine %>% filter(Year != pyear)
test_games <- AllCombine %>% filter(Year == pyear)
model <- lm(amv ~ .,data =model_games[,c(-5,-6,-8,-9,-10,-29)])
test_games$pmv <- predict(model, test_games, type = "response")
plot.new()
test_games %>% ggplot(aes(x=pmv,y=amv)) + geom_point() + 
  abline(c(0,min(test_games$amv)),c(0,max(test_games$amv)))

actual.P <- test_games$amv>0
p.P <- test_games$pmv>0

rp <- confusionMatrix(table(actual.P,p.P))
acc <- c(acc,rp$overall[1])
accy <- c(accy,pyear)
plot(accy,acc)
rp$overall[1]
pyear
```






