---
title: "Madness 2022 Model Test"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, DT, rvest)
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## BPI

```{r}
ESPN_BPI <- data.frame()
for (each_year in seq(from = 2008, to = 2021)){
  for (each_page in seq(from = 1, to = 7)) {
      link = paste0("https://www.espn.com/mens-college-basketball/bpi/_/view/bpi/season/",each_year,"/page/",each_page)
      page <- read_html(link)
      Year <- each_year
      RK <- page %>% html_nodes(".bpi__table td:nth-child(1)") %>% html_text()
      Team <- page %>% html_nodes(".team-names") %>% html_text()
      Conf <- page %>% html_nodes(".align-left+ td.align-left") %>% html_text()
      WL <- page %>% html_nodes(".align-left~ .align-left+ td") %>% html_text()
      BPI_OFF <- page %>% html_nodes("td:nth-child(5)") %>% html_text()
      BPI_DEF <- page %>% html_nodes("td:nth-child(6)") %>% html_text()
      BPI <- page %>% html_nodes("td:nth-child(7)") %>% html_text()
      ESPN_BPI <- rbind(ESPN_BPI,data.frame(Year,RK,Team,Conf,WL,BPI_DEF,BPI_OFF,BPI,stringsAsFactors = FALSE))
  }
}
datatable(ESPN_BPI)
write.csv(ESPN_BPI,"ESPN_BPI.csv")
```

## KenPom

```{r}
KenPom <- data.frame()
for (each_year in seq(from = 2008, to = 2021)){
      link = paste0("https://kenpom.com/index.php?y=",each_year)
      page <- read_html(link)
      Year <- each_year
      RK <- page %>% html_nodes("td.hard_left") %>% html_text()
      Team <- page %>% html_nodes("td.next_left a") %>% html_text()
      Conf <- page %>% html_nodes(".conf a") %>% html_text()
      WL <- page %>% html_nodes("td.wl") %>% html_text()
      AdjEM <- page %>% html_nodes(".wl+ td") %>% html_text()
      AdjO <- page %>% html_nodes(".td-left:nth-child(6)") %>% html_text()
      AdjD <- page %>% html_nodes(".td-left:nth-child(8)") %>% html_text()
      SOSEM <- page %>% html_nodes(".divide:nth-child(14)") %>% html_text()
      SOSO <- page %>% html_nodes(".td-left:nth-child(16)") %>% html_text()
      SOSD <- page %>% html_nodes(".td-left:nth-child(18)") %>% html_text()
      KenPom <- rbind(KenPom,data.frame(Year,RK,Team,Conf,WL,AdjEM,AdjO,AdjD,SOSEM,SOSO,SOSD,stringsAsFactors = FALSE))
}
datatable(KenPom)
write.csv(KenPom,"KenPom.csv")
```

## BasRef

```{r}
BasRef <- data.frame()
for (each_year in seq(from = 2008, to = 2020)){
      link = paste0("https://www.sports-reference.com/cbb/seasons/",each_year,"-ratings.html")
      page <- read_html(link)
      Year <- each_year
      RK <- page %>% html_nodes("th.right") %>% html_text()
      Team <- page %>% html_nodes(".right+ .left a") %>% html_text()
      Conf <- page %>% html_nodes(".left+ .left a") %>% html_text()
      W <- page %>% html_nodes(".right:nth-child(5)") %>% html_text()
      L <- page %>% html_nodes(".right:nth-child(6)") %>% html_text()
      Pts <- page %>% html_nodes(".right:nth-child(7)") %>% html_text()
      Opp <- page %>% html_nodes(".right:nth-child(8)") %>% html_text()
      Mov <- page %>% html_nodes(".right:nth-child(9)") %>% html_text()
      SOS <- page %>% html_nodes(".right:nth-child(11)") %>% html_text()
      OSRS <- page %>% html_nodes(".right:nth-child(13)") %>% html_text()
      DSRS <- page %>% html_nodes(".right:nth-child(14)") %>% html_text()
      SRS <- page %>% html_nodes(".right:nth-child(15)") %>% html_text()
      BasRef <- rbind(BasRef,data.frame(Year,RK,Team,Conf,W,L,Pts,Opp,Mov,SOS,OSRS,DSRS,SRS,stringsAsFactors = FALSE))
}
      link = paste0("https://www.sports-reference.com/cbb/seasons/2021-ratings.html")
      page <- read_html(link)
      Year <- each_year
      RK <- page %>% html_nodes("th.right") %>% html_text()
      Team <- page %>% html_nodes(".right+ .left a") %>% html_text()
      Conf <- page %>% html_nodes(".left+ .left a") %>% html_text()
      W <- page %>% html_nodes(".center+ .right") %>% html_text()
      L <- page %>% html_nodes(".right:nth-child(7)") %>% html_text()
      Pts <- page %>% html_nodes(".right:nth-child(8)") %>% html_text()
      Opp <- page %>% html_nodes(".right:nth-child(9)") %>% html_text()
      Mov <- page %>% html_nodes(".right:nth-child(10)") %>% html_text()
      SOS <- page %>% html_nodes(".right:nth-child(12)") %>% html_text()
      OSRS <- page %>% html_nodes(".right:nth-child(14)") %>% html_text()
      DSRS <- page %>% html_nodes(".right:nth-child(15)") %>% html_text()
      SRS <- page %>% html_nodes(".right:nth-child(16)") %>% html_text()
      BasRef <- rbind(BasRef,data.frame(Year,RK,Team,Conf,W,L,Pts,Opp,Mov,SOS,OSRS,DSRS,SRS,stringsAsFactors = FALSE))
datatable(BasRef)
write.csv(BasRef,"BasRef.csv")
```
