---
title: "Compute Distance from Lat Long"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:
    code_folding: hide
    fig_align: center
    fig_height: 6
    fig_width: 12
    keep_md: yes
editor_options:
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, numform, pracma, DT, plyr)

theme_set(theme_bw())
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## Point to Point Distance Steps

```{r dist_p2p_LL steps}
#Points
lat1 <- -30
lng1 <- -40
lat2 <- 40
lng2 <- 30

#in Radians
lat1r <- lat1*pi/180 #alpha
lng1r <- lng1*pi/180
lat2r <- lat2*pi/180 #gamma
lng2r <- lng2*pi/180
beta <- lng2r - lng1r

#Central angle between points
theta <- acos(cos(lat1r)*cos(lat2r)*cos(beta)+sin(lat1r)*sin(lat2r)) 
er <-6371 #mean radius of the earth in km

#Distance between points
dist <- theta*er

```

## Point to Point Distance Function

```{r dist_p2p_LL func}

dist_p2p_ll <- function(lat1,lng1,lat2,lng2){
  #in Radians
lat1r <- lat1*pi/180 #alpha
lng1r <- lng1*pi/180
lat2r <- lat2*pi/180 #gamma
lng2r <- lng2*pi/180
beta <- lng2r - lng1r

#Central angle between points
theta <- acos(cos(lat1r)*cos(lat2r)*cos(beta)+sin(lat1r)*sin(lat2r)) 
er <-6371 #mean radius of the earth in km

#Distance between points
dist <- theta*er

dist
}
```

```{r test}
dist_p2p_ll(-30,-40,40,30)
```

