---
title: "Top 1000 IMDB"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, rvest, DT)
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## IMDB

https://www.imdb.com/search/title

https://www.imdb.com/search/title/?title_type=feature&user_rating=6.0,10.0&num_votes=20000,&languages=en&sort=user_rating,desc

## Scrape

https://rpubs.com/uky994/578161

https://rstudio-pubs-static.s3.amazonaws.com/299685_5ce4f9fb6fa3476e98fad355623a5f1e.html

```{r}
IMDB <- data.frame()

# https://www.imdb.com/search/title/?title_type=feature&user_rating=6.0,10.0&num_votes=20000,&languages=en&sort=user_rating,desc&start=1&ref_=adv_nxt 

  for (each_page in seq(from = 1, to = 500, by=50)) {
      link = paste0("https://www.imdb.com/search/title/?title_type=feature&user_rating=6.0,10.0&num_votes=20000,&languages=en&sort=user_rating,desc&start=",each_page,"&ref_=adv_nxt")
      page <- read_html(link)
      RK <- page %>% html_nodes(".text-primary") %>% html_text()
      Title <- page %>% html_nodes(".lister-item-header a") %>% html_text()
      Year <- page %>% html_nodes(".text-muted.unbold") %>% html_text()
      Cert <- html_node(html_nodes(page,".lister-item-content"), ".certificate") %>% html_text()
      Runtime <- page %>% html_nodes(".runtime") %>% html_text()
      Genre <- page %>% html_nodes(".genre") %>% html_text()
      Rating <- page %>% html_nodes(".ratings-imdb-rating strong") %>% html_text()
      Meta <- html_node(html_nodes(page,".lister-item-content"), ".favorable") %>% html_text()
      print(each_page)
      IMDB <- rbind(IMDB,data.frame(RK,Title,Year,Runtime,Cert,Genre,Rating,Meta))
  }

datatable(IMDB, rownames = FALSE)
save(IMDB,file = "IMDB.rda")
#write.csv(ESPN_BPI,"ESPN_BPI.csv")
```

```{r}
imdb <- read_html("http://www.imdb.com/search/title?genres=horror&genres=mystery&sort=moviemeter,asc&view=advanced")
title <- imdb %>% html_nodes('.lister-item-header a') %>% html_text()
metascore <- html_node(html_nodes(imdb, '.lister-item-content'), '.ratings-metascore span') %>% html_text()
df <- data.frame(Title = title, Metascore = metascore)
```

