---
title: "2020 Madness Model"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, DT, rpart, DMwR, caret, rpart.plot, rattle, Metrics, ipred, randomForest, gbm, glm.predict,e1071)
theme_set(theme_bw())
confusionMatrix <- caret::confusionMatrix
select <- dplyr::select
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## Team Stats
### Start with individual team stats from 2000 thru 2019

NCAA Season Stats: https://www.sports-reference.com/cbb/seasons/


```{r teamstats}
teams <- read.csv("NCAASeasonTeamStats00to19.csv")
datatable(teams, rownames = FALSE ,extensions = "Responsive",options=list(lengthMenu = c(10,25,68)))
```

## KenPom
### Tack on KenPom 2002-19

Kenpom Rankings: https://kenpom.com/index.php?s=TeamName

```{r KP}
kp <- read.csv("KenPomNCAARankings02to19.csv")
teamcomb <- left_join(kp,teams,by=c("Year"="Year","Team"="Team"))
colsort <- teamcomb %>% select(15,1:14,16:47)
```

## Best Database
### Let's build results and difference of these games

```{r BD}
AG0219FU <- read.csv("AG0219FU.csv")
AG0219FsU <- left_join(AG0219FU,colsort,by = c("Year"="Year","F.Team"="Team")) %>% select(-c("F.AdjEM","Conf"))
colnames(AG0219FsU)[20:62] <- paste("F.", colnames(AG0219FsU)[20:62], sep = "")
AG0219FsUs <- left_join(AG0219FsU,colsort,by = c("Year"="Year","U.Team"="Team")) %>% select(-c("U.AdjEM","Conf"))
colnames(AG0219FsUs)[62:105] <- paste("U.", colnames(AG0219FsUs)[62:105], sep = "")
MainNCAA <- AG0219FsUs %>% select(1:16)
F.NCAA <- AG0219FsUs %>% select(6,9,19,21:29,31:44,46:60)
U.NCAA <- AG0219FsUs %>% select(10,13,63,65:73,75:88,90:104)
F.U.NCAA <- F.NCAA - U.NCAA
colnames(F.U.NCAA) <- paste("F.U.",substring(colnames(F.U.NCAA), 3),sep="")
D.NCAA <- cbind(MainNCAA,F.U.NCAA)
```

## Build the Model 2018

```{r btm}
D.NCAA.18 <- D.NCAA %>% filter(Year < 2019)

go18 <- D.NCAA.18 %>% select(17:57)

# Set seed and create assignment

assignment <- sample(1:2, size = nrow(go18), prob = c(.8,2), replace = TRUE)

# Create a train, validation and tests from the original data frame 
NCAA_train <- go[assignment == 2, ]    # subset NCAA to training indices only
NCAA_test <- go[assignment == 1, ]   # subset NCAA to test indices only

NCAA_model <- lm(F.U.Score ~ .,data =NCAA_train)

p <- predict(NCAA_model, NCAA_test, type = "response")

actual <- NCAA_test$F.U.Score
error <- p - actual

# Calculate RMSE
sqrt(mean((error) ^ 2))

plot(p,actual)

actual.P <- actual>0
p.P <- p>0

confusionMatrix(table(actual.P,p.P))
```

## Predict 2019

```{r p2019}
D.NCAA.19 <- D.NCAA %>% filter(Year == 2019)
########################### Predict Round one ##########################
RoundOne19 <- D.NCAA.19 %>% filter(Round == 1)
m.r1.19 <- RoundOne19 %>% select(1:16)
stats.r1.19 <- RoundOne19 %>% select(17:57)
pred <- predict(NCAA_model, stats.r1.19, type = "response")
actual <- stats.r1.19$F.U.Score
actual.P <- actual>0
p.P <- pred>0
confusionMatrix(table(actual.P,p.P))
pred1 <- ifelse(pred>0,m.r1.19$F.Team,m.r1.19$U.Team)
re <- cbind(m.r1.19,pred1)

########################## Predict Round two ##########################

MainNCAA <- AG0219FsUs %>% select(1:16)
F.NCAA <- AG0219FsUs %>% select(6,9,19,21:29,31:44,46:60)
U.NCAA <- AG0219FsUs %>% select(10,13,63,65:73,75:88,90:104)
F.U.NCAA <- F.NCAA - U.NCAA
colnames(F.U.NCAA) <- paste("F.U.",substring(colnames(F.U.NCAA), 3),sep="")
D.NCAA <- cbind(MainNCAA,F.U.NCAA)

```

