---
title: "Predicting March Madness"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(ggplot2)
library(tidyverse)
library(mosaic)
library(PerformanceAnalytics)
library(stringr)
library(psych) 
library(ggfortify)
library(factoextra)

```

## Background

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
all_Games <- as_tibble(read.csv("withRanking.csv"))
SeasonStats <- as_tibble(read.csv("NCAASeasonTeamStats.csv"))
PAKE <- as_tibble(read.csv("PAKE.csv"))
```

```{r Cds}
fss <- SeasonStats %>% mutate(Year = as.integer(str_extract(Season, "^.{4}")) + 1) %>% setNames(paste0("F.",names(.)))
uss <- SeasonStats %>% mutate(Year = as.integer(str_extract(Season, "^.{4}")) + 1) %>% setNames(paste0("U.",names(.)))
fpake <- PAKE %>% setNames(paste0("F.",names(.)))
upake <- PAKE %>% setNames(paste0("U.",names(.)))
JFS <- left_join(all_Games,fss,by = c("Year" = "F.Year","F.Team" = "F.Team"))
JFS <- left_join(JFS, fpake, by = c("F.Team"="F.TEAM"))
JUS <- left_join(JFS,uss,by = c("Year" = "U.Year","U.Team" = "U.Team"))
JUS <- left_join(JUS, upake, by = c("U.Team"="U.TEAM"))

fs <- JUS %>% dplyr::select(contains("F.")) %>% dplyr::select(1:3,5,8:40)
us <- JUS %>% dplyr::select(contains("U.")) %>% dplyr::select(1:3,5,8:40)
dfu <- fs - us
dfu <- dfu %>% rename_all(funs(str_replace(., "F.", "D."))) %>% tibble::rowid_to_column("ID")
AGwDS <- left_join(all_Games,dfu,by = c("ID" = "ID"))
```

```{r correlation}
bestfit <- AGwDS %>% select(starts_with("D.")) %>% select(4,9,19,36,37)
bestfit$split <- rnorm(nrow(bestfit)) > -1.4
buildfit <- bestfit %>% filter(split)
chart.Correlation(buildfit,histogram=TRUE, pch=19)
```

```{r lm}
mmlm <- lm(D.Score~D.SRS+D.MP+D.PAKE+D.PASE, buildfit)
summary(mmlm)
```

```{r predict}
testfit <- bestfit %>% filter(!split)
testfit$pred <- predict(mmlm, testfit)
testfit$result <- sign(testfit$D.Score)==sign(testfit$pred)

df <- data.frame(table(testfit$result))
colnames(df) <- c('Hit','Freq')
df$Perc <- df$Freq / sum(df$Freq) * 100
df
```

```{r PCA}
# Grab just the D. data
Ddata <- AGwDS %>% select(starts_with("D.")) %>% select(1:18,20:34,36:37) %>% filter(complete.cases(.))
apply(is.na(Ddata),2,which) 
prcomp(Ddata)
summary(prcomp(Ddata))
```

```{r stage2}
D2data<- Ddata%>% select(17:35)
prcomp(D2data)
summary(prcomp(D2data))
```

```{r stage3}
D3data<- D2data%>% select(1:4,13)
prcomp(D3data)
summary(prcomp(D3data))
```

```{r Plot}
fviz_pca_var(prcomp(D3data),
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```

