---
title: "NBA Player Stats 1950-2019"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, plotly)
theme_set(theme_bw())
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

```{r}
#NBA_Player_Stats <- as_tibble(NBA_Player_Season_Stats_1950_2019)
#save(NBA_Player_Stats, file = "NBAPlayerStats1950-2019.rda")
load(file = "NBAPlayerStats1950-2019.rda")
```

https://r4ds.had.co.nz/tibbles.html

```{r}
nycflights13::flights %>% print(n = 10, width = Inf)

NBA_Player_Stats %>% print(n = 10, width = Inf)

```

Extract a column

[[ can extract by name or position; $ only extracts by name but is a little less typing.

```{r}
NPS <- NBA_Player_Stats

NPS[[6]] #Height Column
NPS[["height"]]
NPS$height
NPS %>% .$height

```

https://r4ds.had.co.nz/data-visualisation.html

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

mpg %>% ggplot() + geom_point(aes(displ,hwy))

NPS %>% ggplot() + geom_point(aes(height,weight))

```

##fix the weird heights

```{r}

x <- NPS$height
x <- ifelse(x>300,x/2.54,x)
NPS$height <- x

NPS %>% ggplot() + geom_point(aes(height,weight))

#NPS %>% filter(height <=230 & weight >= 150) %>% select("Year","Player","height")

```

```{r}
#Now the 2019 Jazz in Blue

Jazz2019 <- NPS %>% filter(Tm == "UTA" & Year == 2019)

NPS %>% ggplot(aes(height,weight)) + geom_point() + 
  geom_point(data = Jazz2019,color="red")
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))

mpg %>% ggplot() + geom_point(aes(displ,hwy,color = class))

NPS %>% ggplot() + geom_point(aes(height,weight,color = Pos))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)

NPS %>% ggplot() + geom_point(aes(height,weight,color = Pos)) +
  facet_wrap(~Pos, nrow = 5)

ggplot(NPS) + geom_bar(aes(Pos))

NPS$Pos2 <- fct_collapse(NPS$Pos,
  "C" = c("C", "C-F","C-PF","C-SF"),
  "PF" = c("F","F-C","PF","PF-C","PF-SF"),
  "SF" = c("F-G","SF","SF-PF","SF-PG","SF-SG"),
  "PG" = c("G","PG","PG-SF","PG-SG"),  
  "SG" = c("G-F","SG","SG-PF","SG-PG","SG-SF"))

ggplot(NPS) + geom_bar(aes(Pos2))

NPS %>% ggplot() + geom_point(aes(height,weight,color = Pos2)) +
  facet_wrap(~Pos2)
```

```{r}
NPS %>% ggplot(aes(height,weight)) + geom_point() +
  geom_smooth()
```

```{r}
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))

NPS %>% ggplot(aes(height,weight)) + geom_point(aes(color=Pos2))  + 
  geom_smooth() + facet_wrap(~Pos2)
```


```{r}
ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.min = min,
    fun.max = max,
    fun = median
  )

NPS %>% ggplot() + 
  stat_summary(aes(Pos2,height),
           fun.min = min, fun.max = max, fun = median)
```

```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity))

NPS %>% ggplot() + geom_bar(aes(Pos2, fill = Pos))
```

```{r}
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot() +
  coord_flip()

NPS %>% ggplot() + geom_boxplot(aes(Pos2,height ,fill = Pos2)) +
  coord_flip()
```

```{r}
NPS %>% ggplot() + geom_histogram(aes(PTS))

count <- length(NPS$PTS)
bins <- ceiling(1+3.322*log10(count))

NPS %>% filter(PTS >= 1000) %>% ggplot() + geom_histogram(aes(PTS),bins = bins)

library(plotly)

plot_ly(x = NPS$PTS, type = "histogram", nbinsx = 50,
                marker = list(color = "skyblue2", 
                              line = list(color = "darkgray", 
                                          width = 2)))

```

```{r}
NPS %>% filter(PTS >= 2600) %>% select("Year","Player","PTS") %>% 
  arrange(desc(PTS))
```

```{r}

plot_ly(x = (NPS$VORP), type = "histogram", nbinsx = 50,
                marker = list(color = "skyblue2", 
                              line = list(color = "darkgray", 
                                          width = 2)))
```

```{r}
NPS %>% filter(VORP >= 10) %>% select("Year","Player","VORP") %>% 
  arrange(desc(VORP))
```

## Predicting VORP

```{r}
# Get rid of Blank Columns
NPS <-NPS %>% select_if(~sum(!is.na(.)) > 0)

# VORP started in 1974
VP <- NPS %>% filter(Year >= 1974)

# Get A Train and Test Set
assignment <- sample(1:2, size = nrow(VP), prob = c(.7,.3), 
                     replace = TRUE)
VP_train <- VP[assignment == 1, ] 
VP_test <- VP[assignment == 2, ]   
```

```{r}
#Pick the Columns for predictor variables
sapply(VP, function(x) sum(is.na(x)))

# Now create the model from the train
summary(lm(VORP ~ . ,
           data =VP_train[c(3,6,7,9,13:15,17:23,26:36,40:52,54:55)]))

VORP_model <- lm(VORP ~ . ,
           data =VP_train[c(3,6,7,9,13:15,17:23,26:36,40:52,54:55)]) 

# Now make predictions off the test
predicted <- predict(VORP_model, VP_test, type = "response")
# Compare prediction to actual
actual <- VP_test$VORP

ggplot(data.frame(actual,predicted),aes(x=actual,y=predicted)) + geom_point()

cor(actual,predicted, method = c("pearson"), use = "complete.obs")
```







