---
title: "Gapminder ggAnimate"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse,plotly)
theme_set(theme_bw())
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```


```{r}
NPS2019 <- NBA_Player_Season_Stats_1950_2019 %>% 
  filter(Year == 2019) %>% select("Player","Salary","VORP")
NPS2019 %>%
  plot_ly(x = ~NPS2019$Salary, y = ~NPS2019$VORP, 
    text = ~NPS2019$Player, 
    hoverinfo = "text",type = 'scatter',mode = 'markers') %>%
  layout(xaxis = list(title = "Salary"), yaxis = list(title = "VORP"))
```








