---
title: "Pick the Next Etrade Mutual Fund"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, caret, stocks, BatchGetSymbols, Quandl, scales)
theme_set(theme_bw())
confusionMatrix <- caret::confusionMatrix
select <- dplyr::select
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

###ETRADE All
```{r fun}
days <- Sys.Date() - 0:365
begin <- days[366]
end <- days[1]
load("etrade_all.rda")
EMF <- load_prices(etrade_all$Symbol,from = begin, to = end)

dates <- as.Date(row.names(EMF))
MF <- colnames(EMF)
shares <- etrade_all$Quantity
 
# Multiply prices in EMF by shares to get Value

value <- sweep(EMF, MARGIN=2, shares, `*`)
rownames(value) <- as.Date(dates)
colnames(value) <- MF
value <- data.frame(value)
value$total <- rowSums( value[,1:dim(value)[2]] )
value$inc <- (value$total-value$total[1])/value$total[1] 

NASDAQ <- load_prices(c("^IXIC"),from = begin, to = end)
rownames(NASDAQ) <- as.Date(dates)
colnames(NASDAQ) <- "NASDAQ"
NASDAQ <- data.frame(NASDAQ)
NASDAQ$inc <- (NASDAQ$NASDAQ-NASDAQ$NASDAQ[1])/NASDAQ$NASDAQ[1]

DOW <- load_prices(c("^DJI"),from = begin, to = end)
rownames(DOW) <- as.Date(dates)
colnames(DOW) <- "DOW"
DOW <- data.frame(DOW)
DOW$inc <- (DOW$DOW-DOW$DOW[1])/DOW$DOW[1]

SP <- load_prices(c("^GSPC"),from = begin, to = end)
rownames(SP) <- as.Date(dates)
colnames(SP) <- "SP"
SP <- data.frame(SP)
SP$inc <- (SP$SP-SP$SP[1])/SP$SP[1]

colors <- c("Harmon" = "black", "NASDAQ" = "red", "S&P" = "orange", "DOW" = "blue")

ggplot(data= value, aes(x=dates)) + 
  geom_point(data= value, aes(y=inc, color = "Harmon")) +
  geom_point(data = NASDAQ, aes(y=inc, color = "NASDAQ")) +
  geom_point(data = DOW, aes(y=inc, color = "DOW")) +
  geom_point(data = SP, aes(y=inc, color = "S&P")) +
  geom_smooth(data= value, aes(y=inc, color = "Harmon")) +
  labs(color = "") + scale_color_manual(values = colors)
```

```{r trans}
load("EMF_Trans.rda")

NASDAQ$Dates <- rownames(NASDAQ)
NASDAQ$Date <- as.POSIXct(60*60*24*as.integer(as.character(NASDAQ$Dates)),origin="1970-01-01")
NASDAQ$Date <- as.Date(NASDAQ$Date, format = "%Y-%M-%d")
Etrade_Tx$Date <- as.Date(Etrade_Tx$TransactionDate, format = "%m/%d/%y")
boop <- left_join(NASDAQ,Etrade_Tx %>% 
                    filter(TransactionType %in% c("Sold","Bought")))
ggplot() + 
  geom_point(data= NASDAQ, aes(x=Date,y=NASDAQ), color = "grey", shape = 5) +
  geom_point(data= boop, aes(x=Date,y=NASDAQ, color = TransactionType, 
                              size = Amount, alpha = .5))
```

#Etrade Value Step 1
```{r value}
Etrade_Tx <- Etrade_Tx %>% arrange(desc(Date)) %>% 
  filter(TransactionType %in% c("Sold","Bought")) %>% 
  select(Date,everything())

symbols <- sort(unique(c(MF,Etrade_Tx$Symbol)))
DP <- load_prices(symbols,from = begin, to = end)
MFTrans <- as_tibble(cbind(Date = rownames(DP))) 
MFTrans[,symbols] <- 0
MFTrans <- MFTrans %>% mutate(Date = as.Date(rownames(DP))) %>% 
  arrange(desc(Date))
cm <- ncol(MFTrans)
MFShares <- MFTrans
MFValue <- MFTrans
MFPrices <- MFTrans

for (i in 1:nrow(Etrade_Tx)) {
  r <- which(MFTrans$Date == Etrade_Tx$Date[i])
  c <- Etrade_Tx$Symbol[i]
  MFTrans[r,c] <- Etrade_Tx$Quantity[i]
} #end For Loop

for (i in 1:nrow(etrade_all)){
  c <- etrade_all$Symbol[i]
  MFShares[1,c] <- etrade_all$Quantity[i]
}

for (i in 2:nrow(MFTrans)){
  MFShares[i,2:cm] <- round(MFShares[i-1,2:cm] - MFTrans[i,2:cm],4)
}

MFPrices <- as_tibble(cbind(Date = rownames(DP),DP)) %>% arrange(desc(Date))

for (r in 1:nrow(MFValue)){
  for (c in 2:ncol(MFValue)){
    MFValue[r,c] = MFShares[r,c] * as.numeric(MFPrices[r,c])
  }
}

MFValue <- MFValue %>% mutate(sum = rowSums(.[2:cm]))
MFValue$inv <- 0
MFValue <- MFValue %>% arrange(Date) %>% select(Date,sum,inv,everything())
Etrade_Tx <- Etrade_Tx %>% arrange(Date)
MFValue[1,3] <- MFValue[1,2]
i <- 1
for (r in 2:nrow(MFValue)){
  j <- 1
  if (MFValue$Date[r] < Etrade_Tx$Date[i]){
    MFValue$inv[r] <- MFValue$inv[r-1]
  } else if (MFValue$Date[r] == Etrade_Tx$Date[i]){
    for(j in 1:20){
      if (j == 1 && MFValue$Date[r] == Etrade_Tx$Date[i]){
        MFValue$inv[r] <- MFValue$inv[r-1] - Etrade_Tx$Amount[i]
        i = i + 1
      } else if (j > 1 && MFValue$Date[r] == Etrade_Tx$Date[i]){
        MFValue$inv[r] <- MFValue$inv[r] - Etrade_Tx$Amount[i]
        i = i + 1
      }
    }
  }
}

```

```{r Grph}
MFValue %>% ggplot() + geom_point(aes(x = Date, y = sum)) + 
  geom_point(aes(x = Date, y = inv),color="blue")
```

