---
title: "Investment Strategy"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse)

```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

```{r}
track <- NA
for (x in 1:100) {
  run <- data.frame("Nasdaq"=as.numeric(10000),"Daily"=0,"Action"=NA,"Trade"=0,
                    "Invested"=50000,"Spare"=50000,"Profit"=0,"Left"=0,"Diff"=0)
  row <- run
  for (y in 1:200) {
    daily <- qnorm(runif(1,0,1),12/365,1)
    row[1,"Daily"] <- daily
    row[1,"Nasdaq"] <- run[y,"Nasdaq"] + run[y,"Nasdaq"] * daily/100
    if (daily > 2) {action <- "Sell"} else if (daily < -2) {action <- "Buy"} else {action <- ""}
    row[1,"Action"] <- action
    if (abs(daily) > 2) {trade <- daily * 1000} else {trade <- 0}
    row[1, "Trade"] <- trade
    row[1,"Invested"] <- run[y,"Invested"] + run[y,"Invested"] * daily/100 - trade
    row[1,"Spare"] <- run[y,"Spare"] + trade
    row[1,"Profit"] <- row[1,"Invested"] + row[1,"Spare"] - 100000
    row[1,"Left"] <- 5 * row[1,"Nasdaq"] - 50000
    row[1,"Diff"] <- as.integer(row[1,"Profit"]-row[1,"Left"],2)
    run <- rbind(run, row)
  }
  
  track <- c(track,run[nrow(run),"Diff"])
}

summary(track)
```
















