---
title: "Building the March Madness Dataframe"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, DT)
theme_set(theme_bw())

```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```



## Games 85 to 19

Here are all the march Madness games that have been played since 1985 when March madness first went to a 64 team bracket.

This includes play in games.

```{r atg}
games85 <- read.csv("All_NCAA_Tournament_Games85to19.csv") %>% select(c(2,3,5,6,8:10,12))

datatable(games85, extensions = "Responsive",options=list(lengthMenu = c(10,25,68)))
```

## Rankings and stats

NCAA Season Stats: https://www.sports-reference.com/cbb/seasons/

All Tournament Game Results:

  From which I can get Seed Expectations
  From Which I can get each teams PASE
  
Kenpom Rankings: https://kenpom.com/index.php?s=TeamName

Here are the team season stats since 2000

```{r ras}
teamstats00 <- read.csv("NCAASeasonTeamStats00to19.csv") #%>% select(c(1,3,5,6,8:10,12))

datatable(teamstats00, extensions = "Responsive",options=list(lengthMenu = c(10,25,68)))
```

