---
title: "2020 Madness Model"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, DT)
theme_set(theme_bw())
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## Team Stats
### Start with individual team stats from 2000 thru 2019

NCAA Season Stats: https://www.sports-reference.com/cbb/seasons/


```{r teamstats}
teams <- read.csv("NCAASeasonTeamStats00to19.csv")
datatable(teams, rownames = FALSE ,extensions = "Responsive",options=list(lengthMenu = c(10,25,68)))
```

## KenPom
### Tack on KenPom 2002-19

Kenpom Rankings: https://kenpom.com/index.php?s=TeamName

```{r KP}
kp <- read.csv("KenPomNCAARankings02to19.csv")
teamcomb <- left_join(kp,teams,by=c("Year"="Year","Team"="Team"))
colsort <- teamcomb %>% select(15,1:14,16:47)
```

## 02-18 Tournament games
### Let's build results and difference of these games

```{r results02-18}
AG0219FU <- read.csv("AG0219FU.csv")
AG0219FsU <- left_join(AG0219FU,colsort,by = c("Year"="Year","F.Team"="Team")) %>% select(-c("F.AdjEM","Conf"))
colnames(AG0219FsU)[19:61] <- paste("F.", colnames(AG0219FsU)[19:61], sep = "")
AG0219FsUs <- left_join(AG0219FsU,colsort,by = c("Year"="Year","U.Team"="Team")) %>% select(-c("U.AdjEM","Conf"))
colnames(AG0219FsUs)[63:104] <- paste("U.", colnames(AG0219FsUs)[63:104], sep = "")
```

