---
title: "Chapter 2 R-Markdown"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:
    keep_md: yes
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: center
  pdf_document: default
editor_options:
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse,ggpubr)
theme_set(theme_bw())
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## 2.1 Notes

```{r}
tests <- c(79,81,80,77,73,83,74,93,78,80,75,67,73,77,83,86,90,79,85,83,89,84,82,77,72)

tests <- sort(tests)

length(sort(tests)[tests < 86])/length(tests)
```


### Transforming Data

```{r}
original <- ggplot(data.frame(tests), aes(x = tests)) + geom_dotplot(binwidth = .5)
times2 <- ggplot(data.frame(tests), aes(x = 2 * tests)) + geom_dotplot(binwidth = 1)
plus10 <- ggplot(data.frame(tests), aes(x = tests + 10)) + geom_dotplot(binwidth = .5)

ggarrange(original, times2, plus10, 
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)
```






