---
title: "Top IMDB Movies"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse, rvest, DT)
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## IMDB

https://www.imdb.com/search/title

https://www.imdb.com/search/title/?title_type=feature&user_rating=6.0,10.0&num_votes=20000,&certificates=US%3AG,US%3APG,US%3APG-13,US%3AR,US%3ANC-17&countries=us&languages=en&sort=user_rating,desc

## Scrape

https://rpubs.com/uky994/578161

https://rstudio-pubs-static.s3.amazonaws.com/299685_5ce4f9fb6fa3476e98fad355623a5f1e.html

### Ratings 6.0 to 10.0

```{r}
IMDB <- data.frame()

# https://www.imdb.com/search/title/?title_type=feature&user_rating=6.0,10.0&num_votes=20000,&certificates=US%3AG,US%3APG,US%3APG-13,US%3AR,US%3ANC-17&countries=us&languages=en&sort=user_rating,desc&start=1&ref_=adv_nxt 

  for (each_page in seq(from = 1, to = 3625, by=50)) {
      link = paste0("https://www.imdb.com/search/title/?title_type=feature&user_rating=6.0,10.0&num_votes=20000,&certificates=US%3AG,US%3APG,US%3APG-13,US%3AR,US%3ANC-17&countries=us&languages=en&sort=user_rating,desc&start=",each_page,"&ref_=adv_nxt")
      page <- read_html(link)
      RK <- page %>% html_nodes(".text-primary") %>% html_text()
      Title <- page %>% html_nodes(".lister-item-header a") %>% html_text()
      Year <- page %>% html_nodes(".text-muted.unbold") %>% html_text()
      Cert <- html_node(html_nodes(page,".lister-item-content"), ".certificate") %>% html_text()
      Runtime <- html_node(html_nodes(page,".lister-item-content"), ".runtime") %>% html_text()
      Genre <- html_node(html_nodes(page,".lister-item-content"), ".genre") %>% html_text()
      Rating <- html_node(html_nodes(page,".lister-item-content"), ".ratings-imdb-rating strong") %>% html_text()
      Meta <- html_node(html_nodes(page,".lister-item-content"), ".favorable") %>% html_text()
      Votes <- html_node(html_nodes(page,".lister-item-content"), ".sort-num_votes-visible span:nth-child(2)") %>% html_text()
      Gross <- html_node(html_nodes(page,".lister-item-content"), ".ghost~ .text-muted+ span") %>% html_text()
      Summary <- html_node(html_nodes(page,".lister-item-content"), ".ratings-bar+ .text-muted") %>% html_text()
      Director <- html_node(html_nodes(page,".lister-item-content"), ".text-muted+ p a:nth-child(1)") %>% html_text()
      Star1 <- html_node(html_nodes(page,".lister-item-content"), ".ghost+ a") %>% html_text()
      print(each_page)
      IMDB <- rbind(IMDB,data.frame(RK,Title,Year,Runtime,Cert,Genre,Rating,Meta,Votes,Gross,Summary,Director,Star1))
  }

datatable(IMDB, rownames = FALSE, extensions = 'Responsive')
save(IMDB,file = "IMDB.rda")
#write.csv(ESPN_BPI,"ESPN_BPI.csv")
```

## Clean up

```{r}
# Get the dot off the rank
IMDB$RK <- as.integer(rownames(IMDB))

# Get rid of the parentheses of the year
IMDB$Year <- gsub("\\(I)","",IMDB$Year)
IMDB$Year <- gsub("\\(","",IMDB$Year)
IMDB$Year <- gsub("\\)","",IMDB$Year)
IMDB$Year <- as.integer(IMDB$Year)

# Drop min off of runtime

IMDB$Runtime <- gsub(" min","",IMDB$Runtime)
IMDB$Runtime <- as.integer(IMDB$Runtime)

IMDB$Rating <- as.numeric(IMDB$Rating)
IMDB$Meta <- as.numeric(IMDB$Meta)

IMDB$Votes <- as.integer(gsub("\\,","",IMDB$Votes))

IMDB$Gross <- gsub("\\$","",IMDB$Gross)
IMDB$Gross <- gsub("M","",IMDB$Gross)
IMDB$Gross <- as.numeric(IMDB$Gross)*1000000
save(IMDB,file = "IMDB3.rda")
```



