---
title: "Madness 2022 Model Test"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse)
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

https://rpubs.com/jtxu2008/moneyball

http://www.seanlahman.com/baseball-archive/statistics/

```{r}
batting <- read.csv('Batting.csv')
players <- read.csv("People.csv")
salary <- read.csv("Salaries.csv")
pb <- left_join(players,batting)
pbs <- left_join(pb,salary) 
pbs <- pbs %>% select(14,15,2:13,17,22,25,27:46)
```

```{r}
#Compute Batting Average
pbs$BA <- pbs$H / pbs$AB
#Compute On Base Percentage
pbs$OBP <- (pbs$H + pbs$BB + pbs$HBP) / (pbs$AB + pbs$BB + pbs$HBP + pbs$SF)
#Compute First Base Hits
pbs$X1B <- pbs$H - pbs$X2B - pbs$X3B - pbs$HR
#Compute slugging percentage
pbs$SLG <- (pbs$X1B+2*pbs$X2B+3*pbs$X3B+4*pbs$HR)/pbs$AB
```

##Get These Players

```{r}
these <- pbs %>% select(1:2,16:18,21,37,39)%>%
  filter(AB>100,OBP >= 0,salary <= 8000000,yearID==2002)%>%
  mutate(spo = salary/OBP)
```







