---
title: "Graphics R-Markdown"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:
    keep_md: yes
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: center
  pdf_document: default
editor_options:
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
pacman::p_load(tidyverse)
theme_set(theme_bw())
```

```{r swd, eval=FALSE, echo=FALSE}
# this is set to not run during the knit process
# this sets the working directory to the file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## Stats 6.1 Notes

### Probability Distribution

```{r}
pacman::p_load(tidyverse)
x <- c(0,1,2,3,4,5,6,7,8,9,10)
Prob <- c(.001,.006,.007,.008,.012,.020,.038,.099,.319,.437,.053)
mean <- sum(x*Prob)
var <- sum( (x-mean)^2*Prob)
sd <- sqrt(var)


mean

df <- data.frame(x=x, Prob=Prob)
df %>% ggplot() + geom_histogram(aes(x=x, y=..density..,weight=Prob),
                                 bins = length(x), color = "black")
healthy <- c(.099,.319,.437,.053)
sum(healthy)
```

### grade

```{r}
pacman::p_load(tidyverse)
x <- c(0,1,2,3,4)
Prob <- c(.02,.10,.20,.42,.26)

df <- data.frame(x=x, Prob=Prob)
df %>% ggplot() + geom_histogram(aes(x=x, y=..density..,weight=Prob),
                                 bins = length(x), color = "blue", fill = "orange")

```

### Cars

```{r}
x <- c(0,1,2,3)
Prob <- c(.3,.4,.2,.1)
mean <- sum(x*Prob)
var <- sum( (x-mean)^2*Prob)
sd <- sqrt(var)
```

### four dice

```{r}
x <- c(0,1,2,3,4)
Prob <- c(1/16,4/16,6/16,4/16,1/16)
df <- data.frame(x=x, Prob=Prob)
df %>% ggplot() + geom_histogram(aes(x=x, y=..density..,weight=Prob),
                                 bins = length(x), color = "blue", fill = "orange")
```

### ERROR

```{r}
x <- c(0,1,2,3,4)
Prob <- c(.1,.2,.3,.3,.1)
mean <- sum(x*Prob)
var <- sum( (x-mean)^2*Prob)
sd <- sqrt(var)
```

### Benford

```{r}
x <- c(1,2,3,4,5,6,7,8,9)
Prob <- c(.301,.176,.125,.097,.079,.067,.058,.051,.046)
sum(Prob)
sum(.067,.058,.051,.046)
sum(.301,.176,.125,.097,.079)
sum(.058,.051,.046)
sum(.301,.125,.079,.058,.046)
sum(.301,.125,.079,.058,.051,.046)
df <- data.frame(x=x, Prob=Prob)
df %>% ggplot() + geom_histogram(aes(x=x, y=..density..,weight=Prob),
                                 bins = length(x), color = "blue", fill = "orange")
```

### Housing 9

```{r}
x <- c(1,2,3,4,5,6,7,8,9,10)
Poo <- c(.003,.002,.023,.104,.210,.224,.197,.149,.053,.035)
Pro <- c(.008,.027,.287,.363,.164,.093,.039,.013,.003,.003)
df <- data.frame(x=x, Poo = Poo, Pro = Pro)
colors <- c("Sepal Width" = "blue", "Petal Length" = "red", "Petal Width" = "orange")

df %>% ggplot(aes(x=x)) + geom_histogram(aes(x=x, y=..density..,weight=Poo),
                    bins = length(x), color = "blue", fill = "red", 
                    alpha = .5) +
                  geom_histogram(aes(x=x, y=..density..,weight=Pro),
                    bins = length(x), color = "red", fill = "blue", 
                    alpha =.5) + scale_fill_manual(name="group",values=c("red","blue"),labels=c("a","b")) +
                  geom_label(label="Owners",x=8,y=.2,color = "blue",fill="red") +
                  geom_label(label="Renters",x=2,y=.2,color = "red",fill=halfblue)

mean <- sum(x*Poo)
mean <- sum(x*Pro)

mean <- sum(x*Poo)
sd <- sqrt(sum( (x-mean)^2*Poo))

mean <- sum(x*Pro)
sd <- sqrt(sum( (x-mean)^2*Pro))
```

### cars

```{r}
x<-c(0,1,2,3,4,5)
Px <- c(.09,.36,.35,.13,.05,.02)
mean <- sum(x*Px)
sd <- sqrt(sum( (x-mean)^2*Px))
```

### ferry ride

```{r}
x <- c(0,5,10,15,20,25)
Prob <- c(.02,.05,.08,.16,.27,.42)
df <- data.frame(x=x, Prob=Prob)
df %>% ggplot() + geom_histogram(aes(x=x, y=..density..,weight=Prob),
                                 bins = length(x), color = "blue", fill = "orange")
```







